In [1]:
from matplotlib import *

In [2]:
%matplotlib inline
#With this backend, the output of plotting commands is displayed inline within frontends like the Jupyter notebook, directly below the code cell that produced it.
from pylab import *

In [3]:
import numpy as np

In [4]:
list_data = [1, 2, 3, 4, 5]

for i in range(len(list_data)):
    list_data[i] *= 2
    
list_data

[2, 4, 6, 8, 10]

In [5]:
list_data = [1, 2, 3, 4, 5]
list(map(lambda x:x*2, list_data))

[2, 4, 6, 8, 10]

In [6]:
numpy_data = np.array([1, 2, 3, 4, 5])

2*numpy_data

array([ 2,  4,  6,  8, 10])

In [7]:
def python_multi(n):
    a = list(range(n))
    b = list(range(n))
    c = []
    for i in range(len(a)):
        a[i] = i**2
        b[i] = i**3
        c.append(a[i]+b[i])
    return c

def numpy_multi(n):
    c = np.arange(n)**2 + np.arange(n)**3
    return c

In [8]:
%timeit python_multi(1000)
%timeit numpy_multi(1000)

517 µs ± 2.72 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
7.07 µs ± 26.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


- Functions using numpy librarys is about 215 times faster than those using only the basic ones.

### 3.1.1 Vector

In [10]:
v = np.arange(10)
print(v)
print(v.dtype)
print(v.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


In [11]:
vstep = np.arange(0, 10, 0.5)
vstep

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [12]:
vstep * 10

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

In [13]:
np.linspace(1, 19, 10)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [14]:
np.linspace(1, 19, 10, endpoint=False)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. , 11.8, 13.6, 15.4, 17.2])

In [15]:
from math import e   # import natural logarithm
np.logspace(1, 20, 10, endpoint=False, base=e)

array([2.71828183e+00, 1.81741454e+01, 1.21510418e+02, 8.12405825e+02,
       5.43165959e+03, 3.63155027e+04, 2.42801617e+05, 1.62334599e+06,
       1.08535199e+07, 7.25654884e+07])

In [17]:
np.zeros(20, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.empty(8, int)

array([       1,        1,        0,  5570652,     1304,        0,
       16777984,        0])

In [32]:
np.random.randn(10)   # Return a sample (or samples) from the "standard normal" distribution. standard normal distribution with standard deviation is 1.

array([ 1.38877347, -1.34963474, -0.77198873,  0.62603454, -0.44272435,
        0.43512923,  0.79836137, -0.90248892, -0.15798917,  0.3974142 ])

In [35]:
s = 'Hello Python!'
np.fromstring(s, dtype=int8)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20376\885084285.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s, dtype=int8)


array([ 72, 101, 108, 108, 111,  32,  80, 121, 116, 104, 111, 110,  33],
      dtype=int8)

In [37]:
def multiply99(i, j):
    return (i+1) * (j+1)

np.fromfunction(multiply99, (9, 9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])