In [1]:
from matplotlib import *

In [2]:
%matplotlib inline
#With this backend, the output of plotting commands is displayed inline within frontends like the Jupyter notebook, directly below the code cell that produced it.
from pylab import *

In [3]:
import numpy as np

In [4]:
list_data = [1, 2, 3, 4, 5]

for i in range(len(list_data)):
    list_data[i] *= 2
    
list_data

[2, 4, 6, 8, 10]

In [5]:
list_data = [1, 2, 3, 4, 5]
list(map(lambda x:x*2, list_data))

[2, 4, 6, 8, 10]

In [6]:
numpy_data = np.array([1, 2, 3, 4, 5])

2*numpy_data

array([ 2,  4,  6,  8, 10])

In [7]:
def python_multi(n):
    a = list(range(n))
    b = list(range(n))
    c = []
    for i in range(len(a)):
        a[i] = i**2
        b[i] = i**3
        c.append(a[i]+b[i])
    return c

def numpy_multi(n):
    c = np.arange(n)**2 + np.arange(n)**3
    return c

In [8]:
%timeit python_multi(1000)
%timeit numpy_multi(1000)

517 µs ± 2.72 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
7.07 µs ± 26.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


- Functions using numpy librarys is about 215 times faster than those using only the basic ones.

### 3.1.1 Vector

In [10]:
v = np.arange(10)
print(v)
print(v.dtype)
print(v.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


In [11]:
vstep = np.arange(0, 10, 0.5)
vstep

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [12]:
vstep * 10

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

In [13]:
np.linspace(1, 19, 10)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [14]:
np.linspace(1, 19, 10, endpoint=False)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. , 11.8, 13.6, 15.4, 17.2])

In [15]:
from math import e   # import natural logarithm
np.logspace(1, 20, 10, endpoint=False, base=e)

array([2.71828183e+00, 1.81741454e+01, 1.21510418e+02, 8.12405825e+02,
       5.43165959e+03, 3.63155027e+04, 2.42801617e+05, 1.62334599e+06,
       1.08535199e+07, 7.25654884e+07])

In [17]:
np.zeros(20, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.empty(8, int)

array([       1,        1,        0,  5570652,     1304,        0,
       16777984,        0])

In [32]:
np.random.randn(10)   # Return a sample (or samples) from the "standard normal" distribution. standard normal distribution with standard deviation is 1.

array([ 1.38877347, -1.34963474, -0.77198873,  0.62603454, -0.44272435,
        0.43512923,  0.79836137, -0.90248892, -0.15798917,  0.3974142 ])

In [35]:
s = 'Hello Python!'
np.fromstring(s, dtype=int8)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20376\885084285.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s, dtype=int8)


array([ 72, 101, 108, 108, 111,  32,  80, 121, 116, 104, 111, 110,  33],
      dtype=int8)

In [37]:
def multiply99(i, j):
    return (i+1) * (j+1)

np.fromfunction(multiply99, (9, 9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

### 3.1.2 Arrays

In [38]:
a = np.array([np.arange(3), np.arange(3)])
print(a)
print(a.shape) # matrix shape
print(a.ndim)   # matrix dimension number

[[0 1 2]
 [0 1 2]]
(2, 3)
2


In [39]:
np.identity(9).astype(np.int8)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [40]:
a.tolist()

[[0, 1, 2], [0, 1, 2]]

In [41]:
type(a.tolist())

list

### 3.1.2.1 Data Type and Structural Array

In [72]:
np.datetime64(1660129104, 's')

numpy.datetime64('2022-08-10T10:58:24')

In [73]:
np.datetime64('2022-08-10T10:58:24') - np.datetime64('2022-08-08T10:58:24')

numpy.timedelta64(172800,'s')

#### complete numpy data_type

In [81]:
[e for e in set(np.typeDict.values())]

C:\Users\Admin\AppData\Local\Temp\ipykernel_20376\2495516208.py:1: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  [e for e in set(np.typeDict.values())]


[numpy.object_,
 numpy.complex64,
 numpy.uint16,
 numpy.bytes_,
 numpy.float16,
 numpy.clongdouble,
 numpy.int32,
 numpy.timedelta64,
 numpy.complex128,
 numpy.uintc,
 numpy.int64,
 numpy.void,
 numpy.longdouble,
 numpy.uint32,
 numpy.int16,
 numpy.uint64,
 numpy.intc,
 numpy.int8,
 numpy.uint8,
 numpy.float64,
 numpy.bool_,
 numpy.float32,
 numpy.datetime64,
 numpy.str_]

#### Structural Array

-- 陣列資料的類型可以由使用者自訂
-- 自訂資料類型式一種一直結構資料類型，通常用來記錄一行資料或一系列資料，即結構陣列
-- 結構資料與我們平時進行資料分析的資料形式非常類似

-- 如，需要新增一個購物清單，包含的欄位主要有：商品名稱、購買地點、價格、數量，可以事先使用dtype函數自訂這些欄位的類型

In [99]:
goodslist = np.dtype([('name', np.str_, 50),
                      ('location', np.str_, 50),
                      ('price', np.float16),
                      ('volume', np.int32)])

goodslist

dtype([('name', '<U50'), ('location', '<U50'), ('price', '<f2'), ('volume', '<i4')])

In [100]:
goods = np.array([('Lenovo ThinkPad', 'momoshop.com.tw', 24990, 1),
                  ('Panasonic DD Refrigerator', 'tkec.com.tw', 35900, 2),
                  ('iPhone 13Pro 128G', '24h.pchome.com.tw', 29990, 3),
                  ('Viola Breakfast Meusli', 'urmart.com', 220, 6)], dtype=goodslist)

goods

array([('Lenovo ThinkPad', 'momoshop.com.tw', 24992., 1),
       ('Panasonic DD Refrigerator', 'tkec.com.tw', 35904., 2),
       ('iPhone 13Pro 128G', '24h.pchome.com.tw', 29984., 3),
       ('Viola Breakfast Meusli', 'urmart.com',   220., 6)],
      dtype=[('name', '<U50'), ('location', '<U50'), ('price', '<f2'), ('volume', '<i4')])

-- 還可以使用描述結構類型的各個欄位的dictionary來定義結構陣列
-- 該dictionary有二個keys: names, formats
-- 每個 key 對應的 values 都是一個 list
-- 其中 names 定義結構中每個欄位的名稱
-- 而 formats 則定義每個欄位的類型

In [102]:
goodsdict = np.dtype({'names': ['name', 'location', 'price', 'volume'],
                      'formats': ['S50', 'S30', 'f', 'i']})

goods_new = np.array([('Lenovo ThinkPad', 'momoshop.com.tw', 24990, 1),
                      ('Panasonic DD Refrigerator', 'tkec.com.tw', 35900, 2),
                      ('iPhone 13Pro 128G', '24h.pchome.com.tw', 29990, 3),
                      ('Viola Breakfast Meusli', 'urmart.com', 220, 6)], dtype=goodsdict)

goods_new

array([(b'Lenovo ThinkPad', b'momoshop.com.tw', 24990., 1),
       (b'Panasonic DD Refrigerator', b'tkec.com.tw', 35900., 2),
       (b'iPhone 13Pro 128G', b'24h.pchome.com.tw', 29990., 3),
       (b'Viola Breakfast Meusli', b'urmart.com',   220., 6)],
      dtype=[('name', 'S50'), ('location', 'S30'), ('price', '<f4'), ('volume', '<i4')])

### 3.1.2.2 Indexing and Sliciing

In [82]:
a = np.arange(1, 20, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [83]:
print(a[3])
print(a[1:4])
print(a[:2])
print(a[-2])
print(a[::-1])

7
[3 5 7]
[1 3]
17
[19 17 15 13 11  9  7  5  3  1]


In [84]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [85]:
b.shape

(2, 3, 4)

In [87]:
b[0, 2, :]     # Fetch all elements of 1st layer, 3rd row

array([ 8,  9, 10, 11])

In [88]:
b[0, 2]

array([ 8,  9, 10, 11])

In [89]:
b[0, ...]             # 1st layer

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
b[:, 1]     # any layer, 2nd row

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [93]:
b[:,:,1]     # any layer, any row, 2nd colum

array([[ 1,  5,  9],
       [13, 17, 21]])

In [94]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [95]:
b[0, ::2, -2]

array([ 2, 10])

In [103]:
goods['name']

array(['Lenovo ThinkPad', 'Panasonic DD Refrigerator',
       'iPhone 13Pro 128G', 'Viola Breakfast Meusli'], dtype='<U50')

In [104]:
goods[3]

('Viola Breakfast Meusli', 'urmart.com', 220., 6)

In [105]:
goods[3]['name']

'Viola Breakfast Meusli'

In [106]:
sum(goods['volume'])

12

In [107]:
sum(goods['price']*goods['volume'])

188072.0

#### Indexing by logic condition

In [108]:
b[b>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [109]:
b[~(b>=15)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
b[(b>=5) & (b<=15)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [111]:
b_bool1 = np.array([False, True], dtype=bool)
b[b_bool1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [112]:
b_bool2 = np.array([False, True, True], dtype=bool)
b_bool3 = np.array([False, True, True, False], dtype=bool)
b[b_bool1, b_bool2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [114]:
b[b_bool1, b_bool2, b_bool3]

array([17, 22])

In [117]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### Fancy Indexing

-- 利用整數陣列進行索引，其可使用指定順序對數組提取子集
-- 如，對陣列 b　提取第 0 層 第 1 行 第 2 列 
                    第 0 層 第 2 行 第 3 列 

In [115]:
b[[0], [1, 2], [2, 3]]

array([ 6, 11])

In [119]:
b_slice = b[0, 1, 1:3]
b_slice

array([5, 6])

In [121]:
b_copy = b[0, 1, 1:3].copy()
b_copy

array([5, 6])

In [122]:
b_slice[1] = 666
b_slice

array([  5, 666])

In [123]:
b

array([[[  0,   1,   2,   3],
        [  4,   5, 666,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [124]:
b_copy[1] = 999
b

array([[[  0,   1,   2,   3],
        [  4,   5, 666,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [126]:
ac = np.arange(12)
ac.shape = (2, 2, 3)
ac

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### 3.1.2.4 Sorting

In [127]:
s = np.array([1, 2, 4, 3, 1, 2, 2, 4, 6, 7, 2, 4, 8, 4, 5])
np.sort(s)

array([1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 4, 5, 6, 7, 8])

In [128]:
np.argsort(s)

array([ 0,  4,  1,  5,  6, 10,  3,  2,  7, 11, 13, 14,  8,  9, 12],
      dtype=int64)

In [129]:
s[np.argsort(-s)]

array([8, 7, 6, 5, 4, 4, 4, 4, 3, 2, 2, 2, 2, 1, 1])

In [130]:
s.sort()

print(s, end='')

[1 1 2 2 2 2 3 4 4 4 4 5 6 7 8]

In [131]:
s_r = np.array([3, 23, 52, 34, 52, 3, 6, 645, 34, 7, 85, 23]).reshape(6, 2)

s_r

array([[  3,  23],
       [ 52,  34],
       [ 52,   3],
       [  6, 645],
       [ 34,   7],
       [ 85,  23]])

In [132]:
s_r.sort(axis=1)

s_r

array([[  3,  23],
       [ 34,  52],
       [  3,  52],
       [  6, 645],
       [  7,  34],
       [ 23,  85]])

In [133]:
s_r.sort(axis=0)

s_r

array([[  3,  23],
       [  3,  34],
       [  6,  52],
       [  7,  52],
       [ 23,  85],
       [ 34, 645]])

### 3.1.2.5 Matrix Dimension

In [159]:
b = np.arange(24).reshape(2, 3, 4)

b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [135]:
b.ndim         # 3 dimensions

3

In [136]:
br = np.ravel(b)        # flatten

br

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [137]:
br.ndim       # only 1 dimension

1

In [139]:
brsh = b.reshape(1, 1, 24)

brsh

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [140]:
brsh.ndim         # brsh has 3 dimension

3

In [141]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### Change Dimension

In [155]:
bd = b.reshape(4, 6)

bd

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [156]:
b.shape = (1, 1, 24)

b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [160]:
b.resize(1, 1, 24)

b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])